# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  cart:
    imageOverride:
      digest: "sha256:c9368e178b3dc22df077eb53f0a62e35c4248927605167ffeca6e0c4fc0c5ee2"
