# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  recommendation:
    imageOverride:
      digest: "sha256:c635f3cb22cecb5e81815f06b68a56612aba2c2b296b3e8ca7fbbb885d905bb9"
