# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  kafka:
    imageOverride:
      digest: "sha256:d1673a7442562e1c50c080c613ab915231cda3e9e6a68a96637000158b45fdbd"
