# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  image-provider:
    imageOverride:
      digest: "sha256:eccf3d02aca354849bfac8b0adea2785a328fe7d591d599b995c8024fb7caa4b"
