# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  frontend-proxy:
    imageOverride:
      digest: "sha256:02e8736b627e4ceab275269808819ef17a69943a7f3e418afcd3313f418412b9"
