# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  image-provider:
    imageOverride:
      digest: "sha256:fe38efd5d6432abdc943a55b9c3c086cced1101afaf1b1949494ff4254614a74"
