# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  kafka:
    imageOverride:
      digest: "sha256:a73f7fea609fe5f37bb011fb130bdf6db33adc4c063fc324b9b4b5689fad3cae"
