# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  email:
    imageOverride:
      digest: "sha256:74a2ab7e28ff61532b8c68934363b59cc16d8287157a53aee1e5866b26d36db5"
