# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
mem0:
  image:
    digest: "sha256:65e68b41fd210a1222f2fb11ac4a0ba1c561f87224e4807567cfef6e61a7f272"
