# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  quote:
    imageOverride:
      digest: "sha256:4c3616c0e0147537444e4b70d27ec612fbf2af4a47085fc63c25585ce2fb5743"
