# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  frontend:
    imageOverride:
      digest: "sha256:33fc0a8a566bb301dae3817b0a55ec0fe293aafaf60a50d2d9cd1e9e251f67e0"
