# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  product-catalog:
    imageOverride:
      digest: "sha256:61e17094b2af6c824ea78d19f5d93dfc9cb8003e3baa5edeab58dd8e9f8fa1aa"
