# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  recommendation:
    imageOverride:
      digest: "sha256:e36307357b3f3507199bf6d58d4a50151ac09cf0aa01ab16332c1099dc3e735a"
