# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  opensearch:
    imageOverride:
      digest: "sha256:2b01795223c37781ebcc98ba8bc65b5faef2d1f75dedc4929d26c4030fbc5a79"
