# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  product-catalog:
    imageOverride:
      digest: "sha256:7444502523e1ff417add81fee7d337cd3259281c9e0bc813a1e7e555967098fd"
