# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
aiops:
  enabled: true
  existingSecret: techx-corp-aiops-grafana-webhook
  image:
    digest: "sha256:0a97968c58545b1b5a10a708a9aae184e4eb3d056d927b48ffc7d52c89619e7c"
