# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  currency:
    imageOverride:
      digest: "sha256:9096dd31071de693be7786de81420068705469aaf59b143bc0536e4b99881fd8"
