# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
mem0:
  image:
    digest: "sha256:76dd5bc0b44d4414cfbf8f38811d7616b75b586184cdb4b8c2c60b47997e6397"
