# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  flagd:
    sidecarImageDigests:
      flagd-ui: "sha256:4a00fa450823405df83d3d3bcc061c4b0a713ed7d971b453ff7a51c0af7df874"
