# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  product-reviews:
    imageOverride:
      digest: "sha256:7c6f115a5b6ddb9ff21047348832620e602d59ab48336bf55054f28b24205ae9"
