# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  load-generator:
    imageOverride:
      digest: "sha256:f5ee358636681a93426803db94cfc00fe30e11e4ebabb301f25ac998652b7a6d"
  load-generator-worker:
    imageOverride:
      digest: "sha256:f5ee358636681a93426803db94cfc00fe30e11e4ebabb301f25ac998652b7a6d"
