# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  shopping-copilot:
    imageOverride:
      digest: "sha256:47148e62eb023b4b087d3fc10b939832d53a83efaff5cc0938c423287036b3a7"
