# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  checkout:
    imageOverride:
      digest: "sha256:bfb094a558a1f46a4a668d072d634aa8fe86a300c40878b9e8a0354c1b7a46c7"
