# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  ad:
    imageOverride:
      digest: "sha256:aec365e0ab38848694b7b9f361dabd81bc5370c5d06e40a74d2506be3a932be9"
