# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  currency:
    imageOverride:
      digest: "sha256:79b6c2421c135473ce52d930f01359157394eec7ccc100345abbff5c07398ded"
