# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  opensearch:
    imageOverride:
      digest: "sha256:3ba735ea6ef4f71f4f734bb7137f521dad57f5c93b2f1e29ced1eaad62148e22"
