# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  cart:
    imageOverride:
      digest: "sha256:0e882c6351ac138be4527f1c89a7d4e8f99e5900d967b1014fc73fabac5e3cd5"
