# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  kafka:
    imageOverride:
      digest: "sha256:36672d9c3a89c850090a47df219572a14a1894846ef813fb111e02090a5082ed"
