# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  shopping-copilot:
    imageOverride:
      digest: "sha256:5f13b75f65862119a03180243cc182b30fe073d286b50d324314b7cad1682640"
