# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  checkout:
    imageOverride:
      digest: "sha256:ca491dd2da6ec13d40b4c6e6837851cb512e19dc40d00ed9afe42b6ba6320f6f"
