# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  email:
    imageOverride:
      digest: "sha256:90f2d14b6e1f514b0b3fb15dbd7438fe0b66ae72cf917755394f1fbcdffa0b45"
