# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  fraud-detection:
    imageOverride:
      digest: "sha256:6ca216da266aec37ed45a59f93f66ed40f9e1a1439157ad89b5227bb33afbff7"
