# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
aiops:
  enabled: true
  existingSecret: techx-corp-aiops-grafana-webhook
  image:
    digest: "sha256:41bae8cffb2341f3aa2b46263c14396dfbf971c6a1086ad0dc43ca528c529164"
