# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  opensearch:
    imageOverride:
      digest: "sha256:287da4768b4990ba49f8ed668cff53e20d49fbc0231874950405e5137d2e1fee"
