# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  llm:
    imageOverride:
      digest: "sha256:3dac04e978a6cbe353988046b9c13524c173ddcbb78fa0afeeb5de77bb319458"
