# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  email:
    imageOverride:
      digest: "sha256:30632c0d6a10daf951480ceb4c5444d40f6e0a8b619b8981d05d0710062af6cf"
