# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  llm:
    imageOverride:
      digest: "sha256:143ce8c3090a96699f78ac346827d0b157ffc98c816cae9d4385d1977b0ba56d"
