# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  payment:
    imageOverride:
      digest: "sha256:048161bb3f6529d75387acd37c38cd59a50662d5764bb19b14a2b24964362d23"
