# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  accounting:
    imageOverride:
      digest: "sha256:854f683c4a780560f11ad1b9ca3363a564b336bb84220f5078a89ef91f5ab233"
