# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  product-catalog:
    imageOverride:
      digest: "sha256:60c3f4e4a86c68314d0b01f8d62c38728ad72f7384a4d1c753cb14b6eb00c868"
