# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  accounting:
    imageOverride:
      digest: "sha256:91a01e9af100061be8d6334dd1ab9d0bad810edc3a743b580db61bea150ab420"
