# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  cart:
    imageOverride:
      digest: "sha256:b9a9f31c904c3dfb34bc5fb98788753b6336477ab2b0748cc7a8993b3de08606"
