# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  product-reviews:
    imageOverride:
      digest: "sha256:df8a322a1b59d6c6a51ca27eac6b355917b9eb121d27d789c2817f098655e158"
