# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  frontend-proxy:
    imageOverride:
      digest: "sha256:8342db4a2eb6326825872e076a3606be092fd186dafd0272b257b959a2c16e55"
