# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  fraud-detection:
    imageOverride:
      digest: "sha256:f33442d9e7ac70d1b55c45db573373b7aa9863cb1d6b9fe8e800e2e0b4a55786"
