# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
aiops:
  enabled: true
  existingSecret: techx-corp-aiops-grafana-webhook
  image:
    digest: "sha256:077bdfe6d1d67bbda5e0dd43e513ef5448f7b5c9e2b2a48e84e32b46dc8113f4"
