# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  flagd:
    sidecarImageDigests:
      flagd-ui: "sha256:64db3c3da0323bebc1e2ab501f8cca95b10c9692af95df5fcbe638cf0c7f4758"
