# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  image-provider:
    imageOverride:
      digest: "sha256:47c88c0f37f771cf8295b37342c1dd12cbf0234383154debeec864fabdcc15b9"
