# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  quote:
    imageOverride:
      digest: "sha256:747c40341003aebe927d06a3876f8cd9477d8a1f948a6de119bdc3171ee71fca"
