# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  shipping:
    imageOverride:
      digest: "sha256:6d4bae05a4dc376a8cff710cbfeaef142602654f6cea9a7830a798038cf2c6a9"
