# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  shipping:
    imageOverride:
      digest: "sha256:04679ca0d7ed12c98748096e1ba127eee8d06780837a3942861045c69461ea25"
