# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  fraud-detection:
    imageOverride:
      digest: "sha256:0595ce24a34fe07f53fcd961d087db1b078857bd80c7c6a3c89f6be8ca93398c"
