# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  frontend-proxy:
    imageOverride:
      digest: "sha256:6f5e04266d6ec807514f769c62ccdc119a733a6f23dad7c2b5ec894e06c69edf"
