# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  accounting:
    imageOverride:
      digest: "sha256:61a5d846df401be492aacc7789b74232806c3b8634ba9a80ac6e850892e6c318"
