# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  flagd:
    sidecarImageDigests:
      flagd-ui: "sha256:0f8f19f5580bcdba4056cafeb1b3b8693d573084223d614706b3841774cae7bd"
