# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  quote:
    imageOverride:
      digest: "sha256:90535dd7ae932a95ecd3d8a3399e977ddc4bbf5d86143a529c86d8d3f51628b8"
