# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  llm:
    imageOverride:
      digest: "sha256:301af6d1cfc3918b1fa656ec69a67b061539a03d9224bd5c0e088d916be8f27e"
