# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  frontend:
    imageOverride:
      digest: "sha256:d7d35299cfd6e83673fe479faea959326a66a0a0ce29d2e6de0910be284c2c11"
