# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  ad:
    imageOverride:
      digest: "sha256:61c9ce36c93e6e3feca95478eb96bd03838d72bc56abb1f0663a127affe58d59"
