# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  payment:
    imageOverride:
      digest: "sha256:e8c4a6356024e132c708cb830ac75bbab6117a010a10645561171d25b970d88f"
