# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
mem0:
  image:
    digest: "sha256:3d3d66808fd13935a5aee65d4cac80b8cb0ba6b408d2f24d780c6a385e00d3c0"
