# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  product-reviews:
    imageOverride:
      digest: "sha256:29637dec718fef8b9d9dbf649e6fd0d84b35d105427c84cd49eac28a87f49952"
