# Managed by tf2-corp-platform secure delivery pipeline.
# Change trail: @hungxqt - 2026-07-20 - Selective service digest promote into service-digest/.
components:
  recommendation:
    imageOverride:
      digest: "sha256:55f28f88192a8c40d8702d9eac3cbb67ec11dc82248cd2ed813d7ac68abb359d"
