$ErrorActionPreference = "Stop"; Set-StrictMode -Version Latest
Import-Module (Join-Path $PSScriptRoot "../../scripts/mandate21-fis-approval.psm1") -Force
Import-Module (Join-Path $PSScriptRoot "../../scripts/mandate21-fis-contract.psm1") -Force
function Assert-Rejected($Approval,[string]$Reason,$ValidationArgs) { try { Test-Mandate21Approval -Approval $Approval @ValidationArgs | Out-Null; throw "accepted:$Reason" } catch { if ($_.Exception.Message -eq "accepted:$Reason") { throw "ASSERTION FAILED: $Reason" } } }
$temp = Join-Path ([IO.Path]::GetTempPath()) "m21-approval-test-$PID"; New-Item -ItemType Directory $temp | Out-Null
try {
    $infra = @{ overallStatus='PASS'; accountId='493499579600'; region='us-east-1'; cluster=@{arn='arn:aws:eks:us-east-1:493499579600:cluster/techx-tf2-prod'}; revision=('c'*40) }; $capA=@{ status='PASS'; direction='1a-to-1b'; runId='capacity-a'; evidenceId='capacity-a-capacity'; deployedRevision=('b'*40); argoRevision=('b'*40) }; $capB=@{ status='PASS'; direction='1b-to-1a'; runId='capacity-b'; evidenceId='capacity-b-capacity'; deployedRevision=('b'*40); argoRevision=('b'*40) }; $audit=@{ status='PASS'; alarms=@(@{name='techx-prod-tf2-mandate12-immutable-audit-health-check-errors';state='OK';windowStatus='PASS';periodSeconds=300;evaluationPeriods=2;okDatapoints=2},@{name='techx-prod-tf2-mandate12-immutable-audit-health-lambda-dlq-visible';state='OK';windowStatus='PASS';periodSeconds=300;evaluationPeriods=2;okDatapoints=2},@{name='techx-prod-tf2-mandate12-immutable-audit-control-health';state='OK';windowStatus='PASS';periodSeconds=300;evaluationPeriods=2;okDatapoints=2}) }
    $paths=[ordered]@{ infra="$temp/infra.json"; a="$temp/a.json"; b="$temp/b.json"; audit="$temp/audit.json" }; $infra,$capA,$capB,$audit | ForEach-Object -Begin {$i=0} -Process { $_ | ConvertTo-Json -Depth 20 | Set-Content @($paths.Values)[$i] -Encoding utf8; $i++ }
    $live=@('1a-primary-in','1a-primary-outside','1b-primary-in','1b-primary-outside') | ForEach-Object { [pscustomobject]@{variant=$_;templateId='EXT123456789';revisionSha256=('a'*64);lastUpdateTime='2026-07-29T00:00:00Z'} }
    $now=[DateTimeOffset]::Parse('2026-07-29T12:00:00Z').UtcDateTime; $approval=[pscustomobject]@{schemaVersion=1;accountId='493499579600';region='us-east-1';clusterContext='arn:aws:eks:us-east-1:493499579600:cluster/techx-tf2-prod';chartGitSha=('b'*40);infraGitSha=('c'*40);contractSha256=('d'*64);templates=@($live);evidence=[pscustomobject]@{infraPreflightSha256=Get-FileSha256 $paths.infra;capacity1aTo1bSha256=Get-FileSha256 $paths.a;capacity1bTo1aSha256=Get-FileSha256 $paths.b;auditAlarmSha256=Get-FileSha256 $paths.audit};CapacityApproved='PASS';ChangeApproved='PASS';approvedBy='owner';changeReference='CHG-21';approvedAt='2026-07-29T11:00:00Z';expiresAt='2026-07-29T13:00:00Z'}
    $validationArgs=@{ExpectedAccountId='493499579600';ExpectedRegion='us-east-1';ExpectedClusterContext=$approval.clusterContext;ExpectedChartGitSha=$approval.chartGitSha;ExpectedInfraGitSha=$approval.infraGitSha;ExpectedContractSha256=$approval.contractSha256;LiveTemplates=$live;InfraPreflightPath=$paths.infra;Capacity1aTo1bPath=$paths.a;Capacity1bTo1aPath=$paths.b;AuditEvidencePath=$paths.audit;Now=$now}
    Test-Mandate21Approval -Approval $approval @validationArgs | Out-Null
    $infra.accountId='000000000000'; $infra | ConvertTo-Json -Depth 20 | Set-Content $paths.infra -Encoding utf8; $approval.evidence.infraPreflightSha256=Get-FileSha256 $paths.infra; Assert-Rejected $approval 'wrong embedded infra account' $validationArgs
    $infra.accountId='493499579600'; $infra | ConvertTo-Json -Depth 20 | Set-Content $paths.infra -Encoding utf8; $approval.evidence.infraPreflightSha256=Get-FileSha256 $paths.infra
    $capA.deployedRevision=('e'*40); $capA | ConvertTo-Json -Depth 20 | Set-Content $paths.a -Encoding utf8; $approval.evidence.capacity1aTo1bSha256=Get-FileSha256 $paths.a; Assert-Rejected $approval 'stale capacity revision' $validationArgs
    $capA.deployedRevision=('b'*40); $capA | ConvertTo-Json -Depth 20 | Set-Content $paths.a -Encoding utf8; $approval.evidence.capacity1aTo1bSha256=Get-FileSha256 $paths.a
    $cost=$approval | ConvertTo-Json -Depth 30 | ConvertFrom-Json -Depth 30; $cost | Add-Member CostApproved PASS; Assert-Rejected $cost 'CostApproved must be unknown' $validationArgs
    $duplicate=$approval | ConvertTo-Json -Depth 30 | ConvertFrom-Json -Depth 30; $duplicate.templates=@($duplicate.templates[0],$duplicate.templates[0],$duplicate.templates[0],$duplicate.templates[0]); Assert-Rejected $duplicate 'duplicate variants' $validationArgs
    $expired=$approval | ConvertTo-Json -Depth 30 | ConvertFrom-Json -Depth 30; $expired.expiresAt='2026-07-29T11:30:00Z'; Assert-Rejected $expired 'expired approval' $validationArgs
    $wrong=$approval | ConvertTo-Json -Depth 30 | ConvertFrom-Json -Depth 30; $wrong.accountId='000000000000'; Assert-Rejected $wrong 'wrong account' $validationArgs
} finally { Remove-Item -LiteralPath $temp -Recurse -Force }
Write-Host "FIS approval checks passed."

# Change trail: @hungxqt - 2026-07-29 - Added strict approval acceptance and CostApproved, expiry, and context rejection checks.